name: Haddock Documentation (GitHub Pages)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Prevent overlapping publishes on rapid pushes
concurrency:
  group: haddock-pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:

      - uses: actions/checkout@v4

      - name: Set up build tools
        id: setup
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.12
          cabal-version: 3.16

      - name: Configure
        shell: bash
        run: cabal configure --enable-documentation

      - name: Generate the plan
        shell: bash
        run: cabal build all --dry-run

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        env:
          key: haddock-${{ runner.os }}-${{ steps.setup.outputs.cabal-version }}-${{ steps.setup.outputs.ghc-version }}-${{ github.job }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}

      - name: Install dependencies
        shell: bash
        run: cabal build --only-dependencies -j +RTS -A128m -n2m -N -RTS

      - name: Save dependencies cache
        uses: actions/cache/save@v4
        if: ${{ steps.cache.outputs.cache-primary-key != steps.cache.outputs.cache-matched-key }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build docs
        shell: bash
        run: cabal haddock-project --hackage

      - name: Add .nojekyll (avoid Jekyll processing)
        run: touch haddocks/.nojekyll

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: haddocks

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
